name: Build and Deploy to IBM Cloud Code Engine
# This workflow builds a Docker image for the Quantum Stock Backend and deploys it to IBM Cloud Code Engine.

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version

      - name: Log in to IBM Cloud
        run: |
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r us-south
          ibmcloud target -g Default
          ibmcloud cr login
        env:
          IBMCLOUD_CLI_VERSION: 2.34.1

      - name: Build and push Docker image
        run: |
          docker build -t us.icr.io/quantum-stock-prediction/quantum-stock-prediction:${{ github.sha }} .
          docker push us.icr.io/quantum-stock-prediction/quantum-stock-prediction:${{ github.sha }}

      - name: Deploy to IBM Code Engine
        run: |
          ibmcloud ce project create --name quantum-stock-prediction-project || ibmcloud ce project select --name quantum-stock-prediction-project
          ibmcloud ce project current
          ibmcloud ce application create --name quantum-stock-prediction \
            --image us.icr.io/quantum-stock-prediction/quantum-stock-prediction:${{ github.sha }} \
            --port 8000 \
            --min-scale 1 \
            --max-scale 3 \
            --env IBM_QUANTUM_TOKEN=${{ secrets.IBM_QUANTUM_TOKEN }} \
            --wait-timeout 600