name: Build and Deploy to IBM Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to IBM Cloud Container Registry
      run: |
        echo "${{ secrets.IBM_CLOUD_API_KEY }}" | docker login -u iam --password-stdin icr.io

    - name: Build and push Docker image to IBM Cloud Container Registry
      run: |
        docker build -t icr.io/YOUR_NAMESPACE/quantum-stock-backend:latest .
        docker push icr.io/YOUR_NAMESPACE/quantum-stock-backend:latest

    - name: Deploy to IBM Cloud Code Engine
      run: |
        ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r us-south
        ibmcloud ce project select --name YOUR_CODE_ENGINE_PROJECT
        ibmcloud ce app update --name quantum-stock-api --image icr.io/YOUR_NAMESPACE/quantum-stock-backend:latest --cpu 1 --memory 2G --min-scale 1 --max-scale 3 --port 8000 || \
        ibmcloud ce app create --name quantum-stock-api --image icr.io/YOUR_NAMESPACE/quantum-stock-backend:latest --cpu 1 --memory 2G --min-scale 1 --max-scale 3 --port 8000
